// Government Ministries, Departments, and Agencies (MDAs)
export const MINISTRIES_DEPARTMENTS_AGENCIES = [
  // MINISTRIES
  { value: "mof", label: "Ministry of Finance, Economic Affairs and Investment" },
  { value: "mag", label: "Ministry of the Attorney General and Legal Affairs" },
  { value: "mps", label: "Ministry of the Public Service" },
  { value: "moed", label: "Ministry of Education, Technological and Vocational Training" },
  { value: "moh", label: "Ministry of Health and Wellness" },
  { value: "moha", label: "Ministry of Home Affairs and Information" },
  { value: "mfa", label: "Ministry of Foreign Affairs and Foreign Trade" },
  { value: "mlgrd", label: "Ministry of Local Government and Rural Development" },
  { value: "mhle", label: "Ministry of Housing, Lands and the Environment" },
  { value: "mmw", label: "Ministry of Maritime Affairs and the Blue Economy" },
  { value: "mtw", label: "Ministry of Transport and Works" },
  { value: "mte", label: "Ministry of Tourism and International Transport" },
  { value: "mlss", label: "Ministry of Labour and Social Security" },
  { value: "mycs", label: "Ministry of Youth, Sports and Community Empowerment" },
  { value: "mca", label: "Ministry of Creative Economy, Culture and Sports" },
  { value: "msme", label: "Ministry of Small Business, Entrepreneurship and Commerce" },
  { value: "mag-energy", label: "Ministry of Agriculture, Food and Nutritional Security" },
  { value: "meit", label: "Ministry of Energy and Business Development" },
  { value: "pm-office", label: "Office of the Prime Minister" },
  
  // DEPARTMENTS AND AGENCIES
  { value: "air-nav", label: "Air Navigation Services Department" },
  { value: "analytical", label: "Analytical Services" },
  { value: "bbsa", label: "Barbados Building Standards Authority" },
  { value: "drug-service", label: "Barbados Drug Service" },
  { value: "bgis", label: "Barbados Government Information Service" },
  { value: "prison", label: "Barbados Prison Service" },
  { value: "gender-affairs", label: "Bureau of Gender Affairs" },
  { value: "central-purchasing", label: "Central Purchasing Department" },
  { value: "children-dev", label: "Children's Development Centre" },
  { value: "cooperatives", label: "Co-operatives Department" },
  { value: "czmu", label: "Coastal Zone Management Unit" },
  { value: "community-dev", label: "Community Development Department" },
  { value: "consular", label: "Consular and Diaspora Division" },
  { value: "caipo", label: "Corporate Affairs and Intellectual Property Office" },
  { value: "cjrpu", label: "Criminal Justice Research and Planning Unit" },
  { value: "customs", label: "Customs and Excise Department" },
  { value: "archives", label: "Department of Archives" },
  { value: "commerce", label: "Department of Commerce and Consumer Affairs" },
  { value: "constituency", label: "Department of Constituency Empowerment" },
  { value: "dem", label: "Department of Emergency Management" },
  { value: "youth-affairs", label: "Division of Youth Affairs" },
  { value: "ebc", label: "Electoral & Boundaries Commission" },
  { value: "epd", label: "Environmental Protection Department" },
  { value: "fire-service", label: "Fire Service Department" },
  { value: "fisheries", label: "Fisheries Division" },
  { value: "forensic", label: "Forensic Sciences Centre" },
  { value: "geed", label: "Government Electrical Engineering Department" },
  { value: "gis", label: "Government Industrial School" },
  { value: "gpd", label: "Government Printing Department" },
  { value: "immigration", label: "Immigration Department" },
  { value: "ibfs", label: "International Business & Financial Services Unit" },
  { value: "labour", label: "Labour Department" },
  { value: "land-registration", label: "Land Registration Department" },
  { value: "lands-surveys", label: "Lands and Surveys Department" },
  { value: "licensing", label: "Licensing Authority" },
  { value: "media-resource", label: "Media Resource Department" },
  { value: "met-office", label: "Meteorological Office" },
  { value: "disabilities", label: "National Disabilities Unit" },
  { value: "hiv-aids", label: "National HIV/AIDS Commission" },
  { value: "nis", label: "National Insurance Department" },
  { value: "library", label: "National Library Service" },
  { value: "nutrition", label: "National Nutrition Centre" },
  { value: "natural-heritage", label: "Natural Heritage Department" },
  { value: "opsr", label: "Office of Public Sector Reform" },
  { value: "auditor-general", label: "Office of the Auditor General" },
  { value: "ombudsman", label: "Office of the Ombudsman" },
  { value: "post-office", label: "Post Office" },
  { value: "probation", label: "Probation Department" },
  { value: "psychiatric", label: "Psychiatric Hospital" },
  { value: "registration", label: "Registration Department" },
  { value: "statistics", label: "Statistical Services Department" },
  { value: "sports-council", label: "The National Sports Council" },
  { value: "police", label: "The Police Department" },
  { value: "public-markets", label: "The Public Markets" },
  { value: "sjpi", label: "The Samuel Jackman Prescod Institute of Technology" },
  { value: "school-meals", label: "The School Meals Department" },
  { value: "treasury", label: "Treasury Department" },
  { value: "welfare", label: "Welfare Department" }
]

// Alias for backward compatibility
export const MINISTRIES = MINISTRIES_DEPARTMENTS_AGENCIES
